Repository okp4/ui, pull requests merged in 2022-09, with the labels that each got.

#469 Add invert theme to Icon
  src/ui/atoms/icon/Icon.tsx
  stories/atoms/components/icon/icon.scss
  stories/atoms/components/icon/icon.stories.mdx
Labels: enhancement

#470 Change list color
  src/ui/atoms/button/Button.tsx
  src/ui/atoms/languageSwitcher/LanguageSwitcher.tsx
  src/ui/atoms/listItem/ListItem.tsx
  src/ui/atoms/listItem/listItem.scss
  src/ui/atoms/progressBar/ProgressBar.tsx
  src/ui/atoms/progressBar/progressBar.scss
  src/ui/atoms/toast/Toast.tsx
  src/ui/atoms/typography/Typography.tsx
  src/ui/atoms/typography/typography.scss
  src/ui/styles/palette.scss
  src/ui/styles/themes.scss
  stories/atoms/brand/colors/_exports.module.scss
  stories/atoms/components/list/List.stories.mdx
  stories/atoms/components/listItem/ListItem.stories.mdx
  stories/atoms/components/toast/Toast.stories.mdx
  stories/atoms/components/typography/Typography.stories.mdx
  stories/molecules/components/footer/Footer.stories.mdx
Labels: enhancement

#495 Docs/refactor story theme switches
  stories/atoms/components/button/Button.stories.mdx
  stories/atoms/components/card/Card.stories.mdx
  stories/atoms/components/component.scss
  stories/atoms/components/fileInput/FileInput.stories.mdx
  stories/atoms/components/icon/icon.stories.mdx
  stories/atoms/components/languageSwitcher/LanguageSwitcher.stories.mdx
  stories/atoms/components/list/List.stories.mdx
  stories/atoms/components/listItem/ListItem.stories.mdx
  stories/atoms/components/logo/Logo.stories.mdx
  stories/atoms/components/progressBar/ProgressBar.stories.mdx
  stories/atoms/components/textField/TextField.stories.mdx
  stories/atoms/components/toast/Toast.stories.mdx
  stories/atoms/components/typography/Typography.stories.mdx
  stories/molecules/components/footer/Footer.stories.mdx
  stories/molecules/components/select/Select.stories.mdx
  stories/molecules/components/stepper/Stepper.stories.mdx
  stories/organisms/components/faucet/Faucet.stories.mdx
Labels: documentation, enhancement

#486 Docs/refactor icon story
  stories/atoms/components/icon/icon.scss
  stories/atoms/components/icon/icon.stories.mdx
Labels: documentation, enhancement

#466 Docs/refactor button story
  stories/atoms/components/button/Button.stories.mdx
Labels: documentation, enhancement

#507 Feat: add menu to header
  src/assets/icons/menu-dark.svg
  src/assets/icons/menu-light.svg
  src/assets/icons/sprite.svg
  src/ui/atoms/icon/Icon.tsx
  src/ui/molecules/header/Header.tsx
  src/ui/molecules/header/header.scss
  src/ui/styles/palette.scss
  src/ui/styles/themes.scss
  stories/atoms/brand/colors/_exports.module.scss
  stories/atoms/components/icon/icon.stories.mdx
  stories/molecules/components/header/Header.stories.mdx
  stories/molecules/components/header/header.scss
Labels: enhancement

#536 fix: change immutable list name import
  src/adapters/faucet/primary/eventListeners.spec.ts
  src/adapters/wallet/secondary/InMemoryWalletGateway.ts
  src/adapters/wallet/secondary/KeplrWalletGateway.ts
  src/domain/task/entity/task.ts
  src/domain/wallet/entities/wallet.ts
  src/domain/wallet/store/builder/store.builder.spec.ts
  src/domain/wallet/usecases/enable-wallet/enableWallet.spec.ts
  src/ui/molecules/stepper/Stepper.tsx
  src/ui/providers/storeProvider.tsx
  stories/organisms/components/faucet/store.ts
  stories/organisms/components/filePicker/store.ts
Labels: bug
