Repository okp4/ui, pull requests merged in 2022-10, with the labels that each got.

#514 Feat/improve list and listitem
  src/ui/atoms/list/List.tsx
  src/ui/atoms/list/list.scss
  src/ui/atoms/listItem/ListItem.tsx
  src/ui/atoms/listItem/listItem.scss
  src/ui/organisms/filePicker/FilePicker.tsx
  src/ui/styles/animations.scss
  stories/atoms/components/list/List.stories.mdx
  stories/atoms/components/listItem/ListItem.stories.mdx
Labels: documentation, enhancement

#570 Fix: show code button not working on select story
  stories/molecules/components/select/select.scss
Labels: bug

#575 fix: change sprite generator targets
  package.json
Labels: enhancement

#577 Chore(dev-deps): update babylonjs/core to v5.28.0
  package.json
  yarn.lock
Labels: dependencies

#563 Feat: update header to v2
  src/ui/molecules/header/Header.tsx
  src/ui/molecules/header/header.scss
  src/ui/styles/animations.scss
  stories/molecules/components/header/Header.stories.mdx
  stories/molecules/components/header/header.scss
Labels: enhancement
